server:
  port: 8888
  servlet:
    session:
      cookie:
        http-only: true

spring:
  application:
    name: auth-server
  profiles:
    active: dev
  mvc:
    favicon:
      enabled: false
  jackson:
    # 输出时间为 时间戳
    #    serialization:
    #      write-dates-as-timestamps: true
    # 输出为指定格式字符串
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  task:
    execution:
      thread-name-prefix: auth-task-
      pool:
        core-size: 4
        max-size: 50
        queue-capacity: 10000
    scheduling:
      thread-name-prefix: auth-scheduling-
      pool:
        size: 2


#mybatis
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.berry.authserver.dao.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true

jhipster:
  # CORS is only enabled by default with the "dev" profile, so BrowserSync can access the API
  cors:
    allowed-origins: '*'
    allowed-methods: '*'
    allowed-headers: '*'
    exposed-headers: 'Authorization,Link,X-Total-Count'
    allow-credentials: true
    max-age: 1800

uaa:
  key-store:
    name: keystore.jks
    password: berry123
    alias: keystore

management:
  endpoint:
    health:
      show-details: always
